<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MCNJY01" ignored="0" name="Test(failed)" tests="2" failures="2" timestamp="13 Jul 2019 18:01:22 GMT" time="15.101" errors="0">
  <testcase name="login" time="6.892" classname="datadriven.WordPress">
    <failure type="java.lang.AssertionError" message="expected [Log In ‹ opensourcecms — WordPress] but found [Dashboard ‹ opensourcecms — WordPress]">
      <![CDATA[java.lang.AssertionError: expected [Log In ‹ opensourcecms — WordPress] but found [Dashboard ‹ opensourcecms — WordPress]
	at datadriven.WordPress.login(WordPress.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="6.027" classname="datadriven.WordPress">
    <failure type="java.lang.AssertionError" message="expected [Log In ‹ opensourcecms — WordPress] but found [Dashboard ‹ opensourcecms — WordPress]">
      <![CDATA[java.lang.AssertionError: expected [Log In ‹ opensourcecms — WordPress] but found [Dashboard ‹ opensourcecms — WordPress]
	at datadriven.WordPress.login(WordPress.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test(failed) -->
